python3 -c "from test_prime import test_prime; test_prime(1, False)"
python3 -c "from test_prime import test_prime; test_prime(2, True)"
python3 -c "from test_prime import test_prime; test_prime(3, True)"
python3 -c "from test_prime import test_prime; test_prime(4, False)"
python3 -c "from test_prime import test_prime; test_prime(11, True)"
python3 -c "from test_prime import test_prime; test_prime(25, False)"
python3 -c "from test_prime import test_prime; test_prime(28, False)"
python3 -c "from test_prime import test_prime; test_prime(37, True)"