# Generated by Django 3.1.2 on 2020-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201112_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_dislike',
        ),
        migrations.AddField(
            model_name='dislike',
            name='dislike_post_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dislike',
            name='dislike_user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='like',
            name='like_post_id',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='like',
            name='like_user_id',
            field=models.IntegerField(default=2),
        ),
    ]
