# Generated by Django 3.1.2 on 2020-11-03 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201103_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
