# Generated by Django 3.1.2 on 2020-11-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=64),
        ),
    ]
